version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fabric-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fabric_fault_detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_data:
