import { useEffect, useState } from "react";
import axios from "axios";
import { API_BASE_URL } from "../config.js";
import AppShell from "../components/AppShell";
import CameraCapture from "../components/CameraCapture";

function NonDeterministic() {
  const [file, setFile] = useState(null), [preview, setPreview] = useState(""), [result, setResult] = useState(null), [loading, setLoading] = useState(false), [error, setError] = useState("");
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  const applyFile = (next) => { if(!next) return; if(preview) URL.revokeObjectURL(preview); setFile(next); setPreview(URL.createObjectURL(next)); setResult(null); setError(""); };
  const chooseFile = (e) => applyFile(e.target.files?.[0]);
  const inspect = async () => { if(!file){setError("Please select one label image first.");return;} setLoading(true);setError("");setResult(null); try { const body=new FormData(); body.append("file",file); const {data}=await axios.post(`${API_BASE_URL}/api/non-deterministic/inspect`,body); setResult(data); } catch(e){setError(e.response?.data?.detail||"Inspection failed.");} finally{setLoading(false);} };
  const tone = result?.verdict === "PASS" ? "success" : "error";
  return <AppShell accent="blue" eyebrow="Non-deterministic Label Review" title="Classify a label from one production image" description="Upload one label image and run the trained classifier to identify the most likely fault class and confidence." backTo="/label-inspection" backLabel="Back to label modes" aside={<div className="hero-note"><div className="section-label">Single-image workflow</div><p>The classifier evaluates one image and ranks every known label-fault class.</p></div>}>
    <section className="section-grid section-grid--two"><article className="panel-card"><div className="section-label">Upload image</div><h2>Select the label to inspect</h2><p>Use a clear production label image. No golden reference is required.</p><label className="upload-dropzone"><span className="upload-dropzone__title">Select label image</span><span className="upload-dropzone__text">PNG, JPG, or JPEG</span><input className="file-input" type="file" accept="image/*" onChange={chooseFile} disabled={loading}/></label><CameraCapture onCapture={applyFile} disabled={loading} label="Capture label photo" hint="Use a connected or Raspberry Pi camera to shoot the label directly."/>{file&&<div className="file-meta"><span className="status-pill status-pill--neutral">Image loaded</span><span>{file.name}</span></div>}<div className="preview-frame">{preview?<img src={preview} alt="Label preview" className="preview-image"/>:<div className="empty-state empty-state--compact"><strong>No image selected</strong><span>Your label preview will appear here.</span></div>}</div></article><article className="panel-card panel-card--contrast"><div className="section-label">Inference output</div><h2>Model assessment</h2><p>The result includes the predicted class and ranked alternatives.</p><button className="button button-primary button-primary--wide" onClick={inspect} disabled={loading}>{loading?"Running inference...":"Run non-deterministic inspection"}</button>{error&&<div className="status-banner status-banner--error">{error}</div>}{result?<div className="results-stack"><div className={`status-banner status-banner--${tone}`}><strong>{result.verdict}</strong> · {result.predicted_class} · {Math.round(result.confidence*100)}% confidence</div><div className="metric-grid metric-grid--two"><div className="metric-card"><span className="metric-card__label">Predicted class</span><strong>{result.predicted_class}</strong></div><div className="metric-card"><span className="metric-card__label">Confidence</span><strong>{Math.round(result.confidence*100)}%</strong></div></div><div className="compact-table">{result.predictions?.map((item,index)=><div className="compact-table__row" key={item.class_name}><span><b>{index+1}. {item.class_name}</b></span><strong>{Math.round(item.confidence*100)}%</strong></div>)}</div></div>:<div className="empty-state"><strong>No inference yet</strong><span>Run the inspection to see the model decision.</span></div>}</article></section>
  </AppShell>;
}
export default NonDeterministic;
